info:
  1: |-
    §c§lЗа отсос любой вопрос§r

colors:
  1: |-
    §c§lЦвета..§r

region:
  1: |-
    Гайд: Приват с помощью SexGuard
    §e1: Введение§r
    Добро пожаловать в гайд по использованию привата с помощью плагина §bSexGuard§r! Приват поможет вам защитить свои постройки и территории от других игроков. В этом руководстве мы рассмотрим основные команды и функции плагина.
    §aДля начала убедитесь, что вы §aопределили, какую территорию хотите приватизировать.§r
  2: |-
    §eСоздание привата§r
    Чтобы создать приват, следуйте следующим шагам:

    §a1. Возьмите топорик из дерева (или любой другой предмет, назначенный администратором для обозначения приватов).
    §a2. Выделите первую точку привата, кликнув на блок §lЛКМ.§r
    §a3. Выделите вторую точку, кликнув на другой блок §lПКМ.§r

    §eТеперь у вас должно быть определено две точки, которые образуют прямоугольную область для привата.

    4. Введите команду §b/rg create §a<ИмяПривата>§r.

    §lПример:§r
    /rg create myrg222